### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Ye13ow77z** [openvla/openvla#22] opened 2024-07-07 04:09 UTC
How can I download the dataset used for training？I cant figure out followed the explanation in your github..

**Comment by Ye13ow77z** [comment] 2024-07-07 07:37
emmm I think I have overcome this but... how to solve“ModuleNotFoundError: No module named 'prismatic.conf'”

**Comment by siddk** [comment] 2024-07-08 16:27
Can you run an editable install of the repository (via `pip install -e .` from the root of the repo)?

**Comment by moojink** [comment] 2024-07-10 05:47
Closing the issue; feel free to reopen if the issue is not resolved.

**Closed by moojink** 2024-07-10 05:47 UTC
